version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g @angular/cli@17
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - ng build --configuration production
      - echo "Build completed."
artifacts:
  base-directory: dist  # 빌드 결과물이 생성되는 상위 폴더
  files:
    - '**/*'            # dist 하위의 모든 파일
  discard-paths: no     # 폴더 구조 유지