version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing source dependencies...
      - npm install
  pre_build:
    commands:
      - echo Ready to build front-end application...
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Deploying to S3 Bucket...
      # ./build 대신 ./dist로 변경했습니다 (Vite 대응)
      - aws s3 sync ./dist s3://user40-team6-my-book-manager-s3-bucket --delete
      - echo Invalidating CloudFront cache...
      #- aws cloudfront create-invalidation --distribution-id <자신의-CloudFront-배포-ID> --paths "/*"
      - aws cloudfront create-invalidation --distribution-id E1E9CIV84ALCGR --paths "/*"

artifacts:
  files:
    - '**/*'